[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet build -c Release API_Project/API_Project/API_Project.csproj"]

[phases.start]
cmd = "dotnet run --project API_Project/API_Project/API_Project.csproj"


